### ISSUE TITLE
Use Cases in English and other langs (Roeland Luykx (RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#100]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /usecases-en.html

The Fig. 1 Resource Overview diagram is not shown... image not built?

Roeland Luykx (RALY GmbH)

**Comment by lpg-tech** [comment]
Remove Fig. 1 Resource Overview diagram and place a link to the diagram Resource Overview on the profiles page. Already merged into branch develop, just update changlog.

**Comment by pjolo** [comment]
@lpg-tech: I can't find the link to the diagram on the profile page: https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue100/usecases-en.html

**Comment by lpg-tech** [comment]
Already on develop branch: https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/profiles.html

**Comment by lpg-tech** [comment]
is already on devlop branch: https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/profiles.html

**Comment by pjolo** [comment]
Good
