### ISSUE TITLE
CH LAB Observation Results: eGFR - CKD-EPI(ASR) Profile for females (Michael Rebsamen, Universitätsklinik Balgrist)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#102]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /StructureDefinition-ch-lab-observation-egfr-female.html

The eGFR profiles define/suggest fixed referenceRanges (90 for children and 60 for adults). Is an IG really the right place to (pre-define) such references values? Medical guidelines might change in the future and that would have to be reflected here. Might be difficult to maintain.

Michael Rebsamen, Universitätsklinik Balgrist

**Comment by mrunibe** [comment]
Remark: Applies to all other eGFR profiles as well.

**Comment by lpg-tech** [comment]
Move referenceRanges from dGFR profiles into examples

**Comment by lpg-tech** [comment]
@pjolo branch issue104 already merged into develop

**Comment by pjolo** [comment]
Good
