### ISSUE TITLE
CH LAB Observation Results: eGFR - CKD-EPI(ASR) Profile for females (Michael Rebsamen, Universitätsklinik Balgrist)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#103]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /StructureDefinition-ch-lab-observation-egfr-female.html

The parent of the corresponding profile for male is derived from ChLabObservation_eGFR whereas this is derived from ChLabObservationSingleTest. Should probably be aligned.

Michael Rebsamen, Universitätsklinik Balgrist

**Comment by mrunibe** [comment]
![eGFR_parent](https://github.com/user-attachments/assets/c90184e8-f296-4ec3-aff8-9e0dbf18d968)

**Comment by lpg-tech** [comment]
Merge CDK-EPI profiles for males and females, parent is ChLabObservation_eGFR

**Comment by lpg-tech** [comment]
@pjolo branch issue104 already merged into develop

**Comment by pjolo** [comment]
Good
