### ISSUE TITLE
CH LAB Observation Results: Amount of dedicated profiles

### ISSUE THREAD

**Issue by mrunibe** [hl7ch/ch-lab-report#104]
_IG-feedback as discussed in TC from 25.9.2024_

There are many dedicated profiles for very specific lab results. Some of the profiles are almost identical with just a different LOINC code.

**Example 1: eGFR**
![eGFR](https://github.com/user-attachments/assets/be04cb34-ba78-4d67-ab9c-2e6850c9db2c)

Why not having only one profile (eGFR) and constrain the code to either 98980-6 or 98979-8 in this case?

**Example2: Erythrocyte (Volume vs. Ratio)**
![Erythrocytes](https://github.com/user-attachments/assets/6008f556-6549-43de-98b7-e7a833fe3f1c)

Also here the _volume_ vs. _ratio_ could be differentiated by the LOINC code instead. It is also not clear why only the volume has the additional method (SNOMED 702659008 that would also apply to the _ratio_).

**In general: What is the general strategy? Having a profile for every specific lab test/result?**
Some of the specifics might be more suitable for an example (represented as _Instance_ instead of _Profile_).

**Comment by mrunibe** [comment]
As discussed in TC from 23.10.24:
- The number of eGFR profiles have been reduced from 6 to 3 (of which MDMR might be obsolete)
- Dedicated profiles for Platelet are used in Panel, hence OK. Erroneous differences (_method_) have been aligned
- Enhanced profiles overview: https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/profiles.html

--> Resolved

**Comment by lpg-tech** [comment]
we have now 3 profiles containing data to calculate eGFR: MDRD, CKD-EPI 2009, CKD-EPI 2021. 
Questions: Would they be use by Swiss laboratories? Is MDRD obsolete? Do we need an additional profile, e.g. CKD-EPI 2012? Should we put the referenceRanges into profiles, i.e. are they given to all laboratories by the calculation formula?

**Comment by ziegm** [comment]
Concerning the referenceRanges:
I am firmly convinced that reference ranges do not belong in a profile. If you really find a common reference range, can't you change it at some point? Won't you exclude possible future use cases? If you really want to map something in the profile, then maybe as an example, see identifier.value here: https://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-document-medicationcard.html

**Comment by lpg-tech** [comment]
@pjolo branch issue104 already merged into develop

**Comment by pjolo** [comment]
Good
