### ISSUE TITLE
Fixed coding including display (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#105]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /StructureDefinition-ch-lab-observation-cbc-panel.html

I saw, that the patternCoding does include the display value (e.g. https://fhir.ch/ig/ch-lab-report/StructureDefinition-ch-lab-observation-cbc-panel.html). Best practice would be, to only have the system and code as fixed values, but not the display.

Please check in all other profiles aswell.

Michaela Ziegler, ahdis ag

**Comment by pjolo** [comment]
@lpg-tech :
In these profiles, I found displays that are 1..1. Can you go through all the profiles again? 

https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/StructureDefinition-ch-lab-report-device-analyzer.html
https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/StructureDefinition-ch-lab-report-device-test-kit.html
https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/StructureDefinition-ch-lab-observation-cbc.html
https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/StructureDefinition-ch-lab-observation-cbc-panel.html
https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/StructureDefinition-ch-lab-observation-results-wbc.html

**Comment by lpg-tech** [comment]
Fixed coding, display strings are removed
