### ISSUE TITLE
CodeableConcept.text with fixed value (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#106]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /StructureDefinition-ch-lab-observation-cbc-panel.html

I think it is too strict to require a value for CodeableConcept.text (e.g. https://fhir.ch/ig/ch-lab-report/StructureDefinition-ch-lab-observation-cbc-panel.html). The systems should be able to support/have own text values.

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
remove code.text from all profiles

**Comment by pjolo** [comment]
Good
