### ISSUE TITLE
Must Support (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#107]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /

In the profiles the flag must support is used. But I could not find the description of the meaning for must support in the context of this IG.

(https://github.com/hl7ch/ch-core/wiki/Guidelines-for-Swiss-IG-Development#2-use-of-must-support)

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
add description of meaning for 'must support'
[Resource Profile: CH LAB-Report Device: Analyzer](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue107/StructureDefinition-ch-lab-report-device-analyzer.html)
[Resource Profile: CH LAB-Report Device: TestKit](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue107/StructureDefinition-ch-lab-report-device-test-kit.html)

**Comment by pjolo** [comment]
@lpg-tech : 
The must support flags are not only used in the two profiles you have linked.
I would suggest that you include the explanation of the meaning of the Must Support on the home page, like for example in [CH EMED](https://fhir.ch/ig/ch-emed/index.html#mustsupport)

**Comment by pjolo** [comment]
The changes are good
