### ISSUE TITLE
Home (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#108]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /

Patient Information: Include the patient’s name, age, sex, date of birth, and any other relevant identification details.

is it really sex or would it be the (administrative) gender? if it is sex, could we add gender also in this list?

Michaela Ziegler, ahdis ag

**Comment by pjolo** [comment]
Text has been edited:
[Home ](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue109/index.html)
