### ISSUE TITLE
external links to FHIR spec (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#109]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /document.html

As the IG is based on FHIR v4.0.1 all external links to the FHIR base spec should use this specific version: https://hl7.org/fhir/r4/

Michaela Ziegler, ahdis ag

**Comment by pjolo** [comment]
Links have been fixed
[PR](https://github.com/hl7ch/ch-lab-report/pull/141/files)
