### ISSUE TITLE
Terminology: empty sections (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#110]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /terminology.html

Remove the empty section (CodeSystems, ConceptMaps, NamingSystems) as long as they are not used.

Michaela Ziegler, ahdis ag

**Comment by pjolo** [comment]
The empty sections have been removed.
https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue110/terminology.html
