### ISSUE TITLE
Typos, unify spelling (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#112]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /toc.html

- Home: Foundation: missing point at the very end of the section
- Home: Administrative data -> Data (all other titles start with upper case)
- Home: Order Data: Ordering practitioner, organization, ordering date, recipients -> missing point at the end of the sentence
- Home: Foundation: laboratory Results in Europe -> results
- Terminology: differences with usage of white spaces: ChLab BloodGroup Antibody Screen Tests vs. CH Lab Results Blood Group Antibody
- Terminology: maybe use the common spelling from this IG: CH LAB ... for ChLab BloodGroup Antibody Screen Tests and CH Lab Results Blood Group Antibody
- Examples: Speciment EU Laboratory -> Specimen

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
fix typos, unify spelling

**Comment by pjolo** [comment]
@lpg-tech: Should the titles of the terminologies not be CH LAB-Report...
https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue112/terminology.html

**Comment by lpg-tech** [comment]
adjust title of valueSets, pushed directly into develop
