### ISSUE TITLE
ChLab BloodGroup Antibody Screen Tests (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#113]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /ValueSet-ch-lab-bloodgroup-antibody-screen.html

This value set is not used here; it may be used elsewhere (e.g. specifications and/or implementations that use this content)

Is it not used in the IG (binded to an element)? If no, why is it here?

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
3 Value Sets are used by the Blood Group profile: 

- CH LAB BloodGroup Antibody Result (SNOMED CT coded substances)
- CH LAB BloodGroup Immunohematology Tests (SNOMED CT coded procedures)
- CH LAB BloodGroup Antibody Screen Test Result (LOINC codes)

**Comment by pjolo** [comment]
@lpg-tech For me, the changes are good @ziegm  can you give the final ok thanks:
Profile: [CH LAB Observation Results: Blood Group](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue113/StructureDefinition-ch-lab-observation-blood-group.html)
[Changelog](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue113/changelog.html)
[PR](https://github.com/hl7ch/ch-lab-report/pull/133/files)

**Comment by ziegm** [comment]
It is good, beside that in the profile the display values shouldn't be fixed and required. @lpg-tech could you please adapt that?

**Comment by lpg-tech** [comment]
@pjolo : done

**Comment by pjolo** [comment]
Good
