### ISSUE TITLE
Profiles (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#114]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /profiles.html

[https://www.nejm.org/doi/pdf/10.1056/NEJMoa2102953]
would be just a nice feature, if we could support here an linked link

maybe for that aswell? [LOINC: 98980-6]
https://loinc.org/98980-6/

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
add links to LOINC Codes and NEJM in text of eGFR-CKD-EPI(ASR) 2021 Profile

**Comment by pjolo** [comment]
The links were added.
https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue114/profiles.html
