### ISSUE TITLE
Use Cases in English (Stefan Csomor, Advanced Concepts AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#115]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /usecases-en.html

the resource graphic Resource Overview.svg is apparently missing or incorrect perhaps the space in the filename is a problem

Stefan Csomor, Advanced Concepts AG

**Comment by lpg-tech** [comment]
Already resolved, duplicate of [#100](https://github.com/hl7ch/ch-lab-report/issues/100)
