### ISSUE TITLE
Changelog (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#116]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /changelog.html

Stimmt die Titelebene Publisher note? Und verstehe den Abschnitt nicht ganz.

Michaela Ziegler, ahdis ag

**Comment by ganimedes** [comment]
Das ist der alte changelog. ich denke ich kann diesen Abschnitt löschen .

**Comment by ziegm** [comment]
Kannst du ihn nicht unter das Datum/Version schieben, wo es hingehört? Löschen würde ich nicht, da ja der Changelog die ganze History aufzeigen soll?

**Comment by ganimedes** [comment]
Auch eine Option, allerdings sind einige Links nicht mehr gültig.

**Comment by ziegm** [comment]
Hierfür ist es gut, immer die versionsspezifischen Links zu nehmen, diese bleiben bestehen und zeigen auf diese Version, die gemeint ist.

**Comment by pjolo** [comment]
@lpg-tech: Mir ist noch aufgefallen, dass einige Links auf den develop branche zeigen. Dies müsste noch korrigiert werden.
https://github.com/hl7ch/ch-lab-report/blob/develop/input/pagecontent/changelog.md?plain=1

**Comment by pjolo** [comment]
The changes are gooe.
