### ISSUE TITLE
deprecated discriminator type 'pattern'

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-lab-report#148]
Use type=value instead

for details see https://github.com/hl7ch/ch-core/issues/306

**Comment by lpg-tech** [comment]
@ziegm 
https://github.com/hl7ch/ch-lab-report/pull/117/commits/c0f591beb8e59cdfbeafe364cba7188acd972ebc

**Comment by ziegm** [comment]
good from my side

**Comment by pjolo** [comment]
Adjustments are good
