### ISSUE TITLE
CH Lab Patient: change parent (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-lab-report#53]
@lpg-tech could you please change back the parent profile from CHCorePatientEPR to CHCorePatient. We use the AHVN13 in CH ELM and at the moment it is not allowed that way.

It was with CHCorePatient in the last published version: https://fhir.ch/ig/ch-lab-report/StructureDefinition-ch-lab-patient.html

**Comment by lpg-tech** [comment]
done
