### ISSUE TITLE
Limit image size to 20 megabytes

### ISSUE THREAD

**Issue by lpg-tech** [hl7ch/ch-lab-report#70]
As certain laboratory results (blood counts with images, microbiological findings, etc.) can provide very large amounts of data, the base64 encoded images in this exchange format should be limited here.

**Comment by lpg-tech** [comment]
[base64Binary](https://build.fhir.org/datatypes.html) says:
"There is no specified upper limit to the size of a binary, but systems will have to impose some implementation based limit to the size they support. This should be clearly documented, though there is no computable way for this at this time"

**Comment by lpg-tech** [comment]
Add new Menu-Point Guidance to explain the necessity to limit image/pdf Size

**Comment by ziegm** [comment]
https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue70/guidance.html

**Comment by pjolo** [comment]
> https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue70/guidance.html
> 
> Thank you @lpg-tech for the introduction of this guidance section. I allowed myself to make a few changes: [faa1464](https://github.com/hl7ch/ch-lab-report/commit/faa14646972b5c7efc5b4eed2fbd07de71c425b4)
> 
> If you and @pjolo agree, I'm fine to close the issue.

@ziegm @lpg-tech From my side, the changes are good, thank you very much.

**Comment by lpg-tech** [comment]
@ziegm : thank for the review
