### ISSUE TITLE
Results Blood Group

### ISSUE THREAD

**Issue by lpg-tech** [hl7ch/ch-lab-report#73]
Do we need a complete example? Proposal:  only blood groups and rhesus factor determination as use case
Description of blood bank data exchange:
https://confluence.hl7.org/download/attachments/4489770/Blood%20Bank%20Info%20Exchange%20White%20Paper.pdf?api=v2

2 Valuesets, both have SNOMED CT codes:
*  ValueSet: Results Blood Group - IPS,  value set expansion contains 207 concepts (https://build.fhir.org/ig/HL7/fhir-ips/ValueSet-results-blood-group-uv-ips.html)
*  ValueSet: Results Blood Group - SNOMED CT IPS Free Set,value set contains 13 concepts (https://build.fhir.org/ig/HL7/fhir-ips/ValueSet-results-blood-group-snomed-ct-ips-free-set.html)

Resource BiologicallyDerivedProduct - Content
*  Resource Content (http://hl7.org/fhir/biologicallyderivedproduct.html#resource)

**Comment by lpg-tech** [comment]
10.4.2024: Andreas Buser will participate next VideoCall 22.4.2024 at the beginning.

**Comment by lpg-tech** [comment]
![image004](https://github.com/hl7ch/ch-lab-report/assets/54527242/4aa4eb8f-5e28-4be1-b052-8fc16d850670)

**Comment by lpg-tech** [comment]
Add Instances  BloodGroupDAT and  BloodGroupAntibodies

**Comment by pjolo** [comment]
In agreement with Corina this issue can be closed
