### ISSUE TITLE
Missing loinc codes for CH4 breath test

### ISSUE THREAD

**Issue by lpg-tech** [hl7ch/ch-lab-report#74]
There is only one general LOINC code for  H2 breath test panel
50584-2 "Lactose challenge (hydrogen breath test) panel - Exhaled gas"
but we got all LOINC codes for H2 and CH4 breathtests in the time axis.

It would be nice to get also a general LOINC code for CH4 (and H2S ?) breath test.  Since a request at the Regenstrief Institute will probably take longer, we will leave the breath test example as it is currently implemented.

Request on Regenstrief Instutute done 8.4.2024: 
https://loinc.org/submissions/queue/ Set ID 7220
Lactose challenge panel-hydrogen	-	Pt	Exhl gas	-		[105751-2](https://loinc.org/105751-2)
Lactose challenge panel-methane  	 -	Pt	Exhl gas	-		[105750-4](https://loinc.org/105750-4)

**Comment by lpg-tech** [comment]
split the instance Observation-3-breath-test into 2 observations and assign each the correspondent LOINC code.

**Comment by pjolo** [comment]
The example has been adapted: [Bundle 3-breath-test](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/Bundle-LabResultReport-3-breath-test.json.html)
