### ISSUE TITLE
Move Dependencies to CH ELM (Corina von Känel CISTEC)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#77]
ch.fhir.ig.ch-lab-report#1.0.0-ci-build /

In https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/index.html steht, dass die Beschriebene "Dependencies" für das CH ELM gilt. Kann es ins CH ELM verschoben werden? Im CH ELM gibt es eine ähnliche aber nicht gleiche Grafik

Corina von Känel CISTEC

**Comment by lpg-tech** [comment]
Wir hielten es für wichtig, dass die Benutzer des IG sich über die Dependencies im Klaren sind, und  dass CH-ELM vom CH LAB-Report  abgeleitet wird, anders gesagt, es sind nicht zwei verschiedene Austauschformate. Deshalb ist die Grafik an beiden Orten eingefügt. Inhaltlich sagen sie das gleiche aus.

**Comment by CorinavonKaenel** [comment]
Eine Grafik löschen, wenn kein Informationsgewinn durch die zwei Grafiken.
Mit Text den Unterschied oder die Gemeinsamkeit beschreiben.

**Comment by lpg-tech** [comment]
Die Grafik  wurde  entfernt  und auf die Profiles Seite als Link dargestellt.

**Comment by pjolo** [comment]
Good
