### ISSUE TITLE
CH LAB Observation Blood Group - Definitions (Corina von Känel CISTEC)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#78]
ch.fhir.ig.ch-lab-report#1.0.0-ci-build /StructureDefinition-ch-lab-observation-blood-group-definitions.html

In der CH werden Laborwerte bisher zu 80% als 2 Analysen gemeldet. Um Technische Hürden zu vermeiden würde ich das Binding öffnen. Das heisst, Loinc und Snomed als zwei gleichwertige Umsetzungen deklarieren. Ausserdem ist das Snomed valueset auf welches verwiesen wird nicht vollständig. Der Anbieter, welche Blutgruppe und Rhesus als eine Analyse zurückmeldet und somit Snomed verwendet hat nicht nur Rhesus Pos und Neg sondern auch weak. 
Profile sollten nur vorgeschlagen werden, wenn diese Fachlich geprüft sind. Die Profile sollten beschrieben sein, welchen Zweck sie erfüllen. Hier wäre dieser die Verwendung von SNOMED und das ValueSet, als Zukunftszenario nach entsprechender Weiterentwicklung der LIS.

Corina von Känel CISTEC

**Comment by lpg-tech** [comment]
Habe folgende Änderungen im Profile: ChLabObservationBloodGroup vorgenommen:
1. Statt ValueSet SNOMED CT IPS Free Set das umfangreichere ValueSet: Results Blood Group - IPS verwendet, basierend auf SNOMED 365636006 (Blood group).  IPS Free Set ist ein Subset davon.
2. binding auf preferred belassen.
3. Drei Beispiele dazu:
  [Resultat als Freitext]  (https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/Observation-BloodGroupFreeText.html)
  [Resultat Blutgruppe und Rh kombiniert](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/Observation-BloodGroupSimple.html)
  [Resultat Blutgruppe und Rh separat](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/Observation-BloodGroup.html

**Comment by CorinavonKaenel** [comment]
Gewünschte Anpassung (auch aus erstem Kommentar)
- Purpose beschreiben:
- (Vorteil der Verwendung dieses Profil gegenüber einem Standardergebnis gemäss europäischem LABREPORT?)
- Beispiele so ausarbeiten, dass ohne dass Kennen des Profils, also der Befund gelesen als "europäischem LABREPORT" bspw für die Zusammenfassung der wichtigsten Informationen, die Blutgruppe angezeigt werden kann.
- Damit die Hürde für die Darstellung dieses Ergebnisses möglichst klein ist, sollte der Wert im Befund nicht immer als Freitext und Codiert enthalten sein? Wie würde das im Beispiel aussehen?
- Der Immunhämat Experte im letzten Call hat vermerkt, dass manchmal noch kein Code existiert, also SNOMED/LOINC langsamer ist als die Werte.

**Comment by lpg-tech** [comment]
* removed Observation Profile Bloodgroup
  * added examples Bloodgroup
    * [Blood Group ABO Rh Panel](https://build.fhir.org/ig/hl7ch/ch-lab-report/Observation-BloodGroupPanel.html)
    * [Blood Group Panel with Component ABO and Component Rh](https://build.fhir.org/ig/hl7ch/ch-lab-report/Observation-BloodGroupComponent.html)
    * [Blood Group Rh as free text](https://build.fhir.org/ig/hl7ch/ch-lab-report/Observation-BloodGroupFreeText.html)
    * [Blood Group Rh combined](https://build.fhir.org/ig/hl7ch/ch-lab-report/Observation-BloodGroupSimple.html)

**Comment by lpg-tech** [comment]
Example has been removed as no data exchange possible without agreement. 
Currently, the blood group results, as they are output in the LIS, must be agreed in advance.

**Comment by lpg-tech** [comment]
Example 'Blood Group Rh as free text' has been removed as no data exchange possible without agreement. 
Currently, the entries of blood group results, as they are output in the LIS, must be agreed in advance, while they ar not coded

**Comment by lpg-tech** [comment]
@CorinavonKaenel 
Das erste Beispiel meldet wohl die Eigenschaften einer Blutkonserve (Ressource: BiologicallyDerivedProduct). Das werden wir später umsetzen.
Die beiden folgenden Beispiele sind hier umgesetzt:

- [Blood Group Panel with Component Antibody screen test and DAT test](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue116/Observation-BloodGroupCompAB0CompRhDAT.html)
- [Blood Group Panel with Component ABO, Component RhD, Rh Genotype and Result Antibodies](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/issue116/Observation-BloodGroupCompAB0CompRhDAntibodies.html)

**Comment by lpg-tech** [comment]
Das Blutgruppenpanel steht eigentlich nur für zukünftige Verwendungen mit speziellen Valusets für Blutbanken. 
Das Freitext Beispiel macht aus meiner Sicht keinen Sinn. Wir wollen ja einen Standard, der eindeutige Ergebnisse übermitteln kann ohne vorherige Absprachte. Eigene Freitext-Bezeichner sind aber immer möglich bei einem CodeableConcept, der Code sollte aber mitgeliefert werden.
Das Beispiel für Blutkonserven habe ich mit Absicht weggelassen, weil die resource BiologicallyDerivedProduct  in FHIR 5 und 6 ganz bessere Elemente hat.  Werde es aber trotzdem noch versuchen mit der FHIR 4.

**Comment by CorinavonKaenel** [comment]
Blutgruppenanalysen und weitere immunhämatologische Analysen werden in jedem Spitallabor und Privatlabor durchgeführt. Spezialisierte nur in SRK Laboren.

Betreffend Ergebnisse ohne Codierung
Es geht hier um eine Abbildung von Laborwerten in HL7 FHIR und nicht um ein SNOMED oder LOINC Projekt.
Sowohl in HL7 FHIR wie auch in HL7 V2 können Ergebnisse codiert oder uncodiert übermittelt werden.

Aus meiner Sicht entspricht es nicht dem Bedürfnis der Labore und IT-Anbieter, dass ein Ergebnis nur codiert übermittelt werden kann. Zentral ist, dass die Informationen aus dem Laborbefund einem Arzt im KIS, PIS oder EPD dargestellt werden können so wie sie im Labor validiert wurden. Damit es keine 1:1 Absprachen zwischen Sender und Empfänger benötigt muss klar sein, wo die Information für den Befundleser steht. Dass das PIS, KIS, EPD die Information zusätzlich codiert erhält ist ein Vorteil bzw Bedingung für Auswertungen und bspw CDS Systeme. Aus meiner Sicht sollen auch Labore FHIR nutzen können, welche ihre Blutgruppen als Blutgruppe A, B, 0, AB senden möchten und nicht als SNOMED codiert.

Wenn ich mich richtig erinnere, hat niemand aus den Meetings den Bedarf gehabt, dass zum aktuellen Zeitpunkt Blutprodukte-Informationen übermittelt werden können. In HL7 V2 gibt es einen eigenen Trigger Event hierfür: HL7 V2 BPS. Ich habe nicht den Eindruck, dass dies zum CH LAB Report gehört.

Beste Grüsse
Corina

**Comment by lpg-tech** [comment]
@CorinavonKaenel 
Die 3 Beispiele(https://github.com/hl7ch/ch-lab-report/issues/73) sind nun jeweils mit codierten und freetext Resultaten umgesetzt (https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/artifacts.html#example-example-instances). 
BiologicallyDerivedProduct lasse ich weg.

**Comment by pjolo** [comment]
In agreement with Corina this issue can be closed
