### ISSUE TITLE
Profile: ChLabObservationBloodGroup

### ISSUE THREAD

**Issue by lpg-tech** [hl7ch/ch-lab-report#92]
This profile needs ValueSets describing BloodGroup Antigenes and Antibodies and BloodGroup Antibody screening tests:
  -  [ValueSet: Results Blood Group - SNOMED CT IPS Free Set](http://hl7.org/fhir/uv/ips/ValueSet/results-blood-group-snomed-ct-ips-free-set)
  -  [ValueSet: Results Blood Group - IPS](http://hl7.org/fhir/uv/ips/ValueSet/results-blood-group-uv-ips)
  -  [ValueSets: CH LAB  ](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/terminology.html)
 
These Valuesets need to be approved by the national specialist organization:
[SVTM, Schweizerische Vereinigung für Transfusionsmedizin](https://www.svtm-asmt.ch/de)

**Comment by lpg-tech** [comment]
Add 3 additional ValueSets as candidates into Profile:
* CH LAB BloodGroup Antibody Screen Test Result (LOINC codes) 
* CH LAB BloodGroup Immunohematology Tests (SNOMED CT coded procedures)
* CH LAB BloodGroup Antibody Result (SNOMED CT coded substances)

Valuesets are already in develop branch

**Comment by pjolo** [comment]
Good
[Value Sets](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/terminology.html)
Profile: [CH LAB Observation Results CBC Panel - Blood by Automated count, Results in sliced component](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/StructureDefinition-ch-lab-observation-cbc.html) 
[Changelog](https://build.fhir.org/ig/hl7ch/ch-lab-report/branches/develop/changelog.html)
