### ISSUE TITLE
CH LAB Composition - Profile Status (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#93]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /StructureDefinition-ch-lab-report-composition.html

The status of this profile is "Trial use", the https://fhir.ch/ig/ch-lab-report/StructureDefinition-ch-lab-report-document.html has status "Active". 
Please check, that all profiles have the same status (or describe, why there is a difference).

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
Outcomment SetFmmandStatusRule in all profiles

**Comment by lpg-tech** [comment]
@pjolo: branch is already merged into develop

**Comment by pjolo** [comment]
@lpg-tech 
Has the status been changed for all profiles? 
There is no branch for merging for this issue.

**Comment by lpg-tech** [comment]
All "insert SetFmmandStatusRule ( 2, trial-use)" in profiles are outcommented, so status is active. The branch is alrady merged into branch develop and deleted. Issue can be closed.

**Comment by pjolo** [comment]
Good
