### ISSUE TITLE
Bundle 2-electrophoresis - JSON Representation (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#94]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /Bundle-LabResultReport-2-electrophoresis.json.html

Why is the section "Laboratory examinations" empty?

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
Section is not empty, contains subsection  "Chemistry studies (set)"

**Comment by ziegm** [comment]
Yes, true. Sorry, did look something wrong then. So the issue can be closed without adaption (except changelog) from my side.

**Comment by lpg-tech** [comment]
@pjolo : ready

**Comment by pjolo** [comment]
@lpg-tech 
Here, too, I cannot see if the changes have been made.

**Comment by pjolo** [comment]
Good
