### ISSUE TITLE
Specimen.type (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#95]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /StructureDefinition-ch-lab-specimen.html

The request is to reduce the minimum cardinality of Specimen.type to 0. I do have a use case, where i need to represent the Specimen, but do not have detailed information about the type. EU LAB has it also to 0 instead 1.

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
reduce the minimum cardinality of Specimen.type to 0

**Comment by pjolo** [comment]
Pull Request has been merged, so this issue can be closed.
