### ISSUE TITLE
CH LAB Specimen: reduce min cardinality of specimen.type to 0 (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#96]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /StructureDefinition-ch-lab-specimen.html

The EU Lab had a minium requirement for specimen.type of 1, however for the CH ELM Use Case we have cases where we cannot provide seperatly the specimen.type it is already implied through the LOINC code.

We entered this in the EU Ballot and the minum cardinality is now one (see https://hl7.eu/fhir/laboratory/0.1.0/StructureDefinition-Specimen-eu-lab.html), can we also reduce the min cardinality to 0 for the swiss exchange format?

see issue also in CH ELM https://github.com/ahdis/ch-elm/issues/31

Oliver Egger, ahdis ag

**Comment by lpg-tech** [comment]
@pjolo: ready

**Comment by pjolo** [comment]
@lpg-tech 
I can't see what the changes are, as no branch is linked either, so it's up to you to decide if the issue is resolved.

**Comment by lpg-tech** [comment]
@pjolo : updated changelog, no amendment, since duplicate

**Comment by pjolo** [comment]
Good
