### ISSUE TITLE
Typo: Blood Group Panel with Component ABO and Component Rh (Test)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#97]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /Observation-BloodGroupComponent.html

The link name to SNOMED is incorrect for method and value.
It is not SNOWMED but SNOMED.

![image](https://github.com/user-attachments/assets/0504b233-7907-4d62-b5be-8a0dca54b512)

**Comment by pjolo** [comment]
Typo with SNOWMED was triggered by the IG Publisher.
See related bug in FHIR Core: https://github.com/hapifhir/org.hl7.fhir.core/pull/1623/files
The typo has been corrected in the meantime and this issue has been added to the changelog https://fhir.ch/ig/ch-lab-report/changelog.html
