### ISSUE TITLE
CH LAB ServiceRequest: Laboratory Order (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-lab-report#99]
ch.fhir.ig.ch-lab-report#1.0.0-ballot /StructureDefinition-ch-lab-report-servicerequest.html

Is there a reason, why the imposeProfile extension (to EU LAB) is missing for the ServiceRequest profile?

Michaela Ziegler, ahdis ag

**Comment by lpg-tech** [comment]
Insert  'imposeProfile extension (to EU LAB) is missing for the ServiceRequest', adapt  ChLabReportServiceRequest

**Comment by pjolo** [comment]
This issue was resolved by the pull request https://github.com/hl7ch/ch-lab-report/pull/127#event-14969968436
